if: branch = master OR tag =~ ^v[0-9]

language: scala
jdk:
- openjdk8
- openjdk10
scala:
- 2.12.10
- 2.13.1
script:
- sbt validate
jobs:
  include:
  - stage: publish
    script: sbt bintrayEnsureCredentials bintrayEnsureLicenses +publish +bintrayRelease
    jdk: openjdk8
    if: type = push AND tag IS present
cache:
  directories:
  # Cache SBT launcher and SBT dependencies
  - $HOME/.sbt/1.0/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
before_cache:
- du -h -d 1 $HOME/.ivy2/cache
- du -h -d 2 $HOME/.sbt/
# Delete transient files to avoid needless re-caching
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
