name: CI
on:
  pull_request:
    branches: ['*']
  push:
    branches: ['main']
    tags: [v*]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: sbt/setup-sbt@v1
    - name: Coursier cache
      uses: coursier/cache-action@v7
    - name: Build and test
      run: |
        sbt -v -Dfile.encoding=UTF-8 +validate
        rm -rf "$HOME/.ivy2/local" || true
        find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
        find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
        find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
        find $HOME/.sbt                              -name "*.lock"               -delete || true
